export interface ICssProperty {
  $borderRadius?: string;
  $height?: string;
  $minHeight?: string;
  $width?: string;
  $minWidth?: string;
  $padding?: string;
  $margin?: string;
  $fontSize?: string;
  $lineHeight?: string;
  $fontWeight?: string;
  $background?: string;
  $border?: string;
  $borderColor?: string;
  $borderBottom?: string;
  $borderTop?: string;
  $borderLeft?: string;
  $backgroundClip?: string;
  $backgroundOrigin?: string;
  $addonsHeight?: string;
  $rowHeight?: string;
  $rowMargin?: string;
  $secondary?: boolean;
  $warning?: boolean;
  $disabledColor?: string;
  $disabledBorderColor?: string;
  $default?: boolean;
  $whiteStyle?: boolean;
  $maxWidth?: string;
  $maxHeight?: string;
  $display?: string;
  $color?: string;
  $transform?: string;
  $right?: string | number;
  $left?: string | number;
  $top?: string | number;
  $bottom?: string | number;
  $position?: string;
  $zIndex?: string;
  $alignSelf?: string;
  $verticalAlign?: string;
  $ellipsis?: boolean;
  $alignItems?: string;
  $accent?: boolean;
  $transition?: string;
  $cursor?: string;
  $pointerEvents?: string;
  $opacity?: number;
  $justifyContent?: string;
  $textAlign?: string;
  $textDecoration?: string;
  $boxShadow?: string;
  $flexDirection?: string;
  $overflowY?: string;
  $backgroundHover?: string;
  $borderHover?: string;
  $whiteSpace?: string;
  $flex?: string;
  $colorHover?: string;
  disabled?: boolean;
  src?: string;
  width?: string;
  height?: string;
  $fontColor?: string;
}
